# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('start', models.DateTimeField(verbose_name='Start Date')),
                ('end', models.DateTimeField(verbose_name='End Date')),
                ('total_assigned', models.PositiveSmallIntegerField(default=0, verbose_name='Total Number Of Tasks Assigned')),
                ('total_reassigned', models.PositiveSmallIntegerField(default=0, verbose_name='Total Number Of Tasks Reassigned')),
                ('total_accepted', models.PositiveSmallIntegerField(default=0, verbose_name='Total Number Of Tasks Assigned')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.BooleanField(verbose_name='High Priority')),
                ('status', models.CharField(default='Pending', max_length=15, verbose_name='Status')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category (Optional)')),
                ('status', models.CharField(default='Free', max_length=15, verbose_name='Status')),
                ('num_assigned', models.PositiveSmallIntegerField(default=0, verbose_name='Number Of Tasks Assigned')),
                ('num_accepted', models.PositiveSmallIntegerField(default=0, verbose_name='Number Of Tasks Accepted')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventful.Volunteer'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteer',
            unique_together=set([('organizer', 'name'), ('organizer', 'phone')]),
        ),
    ]
