# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 03:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventful.Volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
