# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0003_auto_20170429_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
