# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0004_auto_20170429_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highPriority',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='High'),
        ),
        migrations.AddField(
            model_name='event',
            name='lowPriority',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Low'),
        ),
    ]
