# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0008_auto_20170505_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='category',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Category (Optional)'),
        ),
    ]
