# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0009_auto_20170505_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latest_assignment',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 20, 43, 22, 896241), verbose_name='Time of Latest Assignment'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_responsetime',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Response Time'),
        ),
    ]
