# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0013_auto_20170505_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='latest_assignment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Latest Assignment'),
        ),
    ]
