# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0015_auto_20170510_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='first',
            field=models.BooleanField(default=True, verbose_name='First Instance'),
        ),
    ]
