# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0017_auto_20170510_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='unsubscribed',
            field=models.BooleanField(default=False, verbose_name='Unsubscribed'),
        ),
    ]
