# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0018_volunteer_unsubscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
    ]
